### ISSUE TITLE
recognize "bibentry" and "nobibliography"

### ISSUE THREAD

**Issue by hamogu** [yymao/adstex#11]
When writing proposals, I sometimes save space with the bibentry package. In that case, the bibliography file is marked with the `\nobibliography{filename}` command instead of `\bibliography{filename}` and references are inserted with `\bibentry{key}` instead of `\cite{key}`. I can make the bibentry syntax work by modifying the definitions for `_re_bib` and `_re_cite` in the code, but I can't figure out how to make a regex that would find both `bibentry` and `cite` or `biblography` and `nobiblography` with the same regex. You are clearly a wizzard here, so maybe you can add that.

**Comment by yymao** [comment]
@hamogu thanks for the suggestion! This is now implemented in v0.3.3. You can get this version by running `pip install adstex==0.3.3`

**Comment by hamogu** [comment]
Great, thanks! And by looking at how you did it, I also learned something new about regexes ;-)

**Comment by yymao** [comment]
No problem! I highly recommend https://regex101.com/ if at some point you are interested in learning more about regex :)
