### ISSUE TITLE
Bug when key exists in others

### ISSUE THREAD

**Issue by syrte** [yymao/adstex#14]
https://github.com/yymao/adstex/blob/5723da435de17ac65cfb7181c8dbab0d34c75a7a/adstex.py#L394-L398

When `key_exists_in_others` is True and `key_exists` is False, the procedure will crash at `bibcode = extract_bibcode(bib.entries_dict[key])`, because `bib.entries_dict` does not have `key` there.

**Comment by yymao** [comment]
Thanks for the bug report! Fixed by #15.
