### ISSUE TITLE
issue opening the ADS beta site on firefox

### ISSUE THREAD

**Issue by johannct** [yymao/adstex#2]
I just cloned adstex and installed it, and managed to proceed with the ADSbeta registration/token retrieval with chromium, but on firefox I get a 404.html not found error.... Any idea? It might have to do with a local config, but I did not find which one (nor do I see anything obvious on the chromium side).

**Comment by yymao** [comment]
@johannct can you provide a bit more detail? Which page did you try to visit on Firefox and get an 404 Error? I've tried all the links in the README with Firefox and Chrome and all of them work for me.

**Comment by johannct** [comment]
the entry point : https://ui.adsabs.harvard.edu/

**Comment by johannct** [comment]
firefox 57.0.1 (64-bit)

**Comment by yymao** [comment]
Hmm, I have no problem visiting the said page with Firebox 57.0.3 (64-bit) on Linux. My officemate also have no problem visiting it with Firebox on Mac OS. Not sure what's wrong here.

**Comment by johannct** [comment]
me neither, and I do not get any hint...

**Comment by johannct** [comment]
ok I ran a firefox refresh and now it is ok.... Perhaps an addon dysfunctioning. Hard to tell. Closing

**Comment by yymao** [comment]
Hmm maybe try clearing browser cache? If the problem persists, maybe try contanting [ADS Help](https://adsabs.github.io/help/)? 

I'm closing this issue since it does not seem to an issue with the `adstex` package.
