### ISSUE TITLE
Line breaks in citations cause failed capturing of bib keys

### ISSUE THREAD

**Issue by birnstiel** [yymao/adstex#22]
`natbib` citations such as 

    \citep[see also][]{Aauthor2019,Bauthor2020}

are not correctly recognized if a line-break occurs. Some authors/text editors might hard-wrap this citation at the space:

    Lorem ipsum dolor sit amet, consectetur adipiscing \citep[see
    also][]{Aauthor2019,Bauthor2020} eget risus sollicitudin neque
    imperdiet suscipit. 

`adstex` fails to detect those bib keys.

**Comment by yymao** [comment]
@birnstiel Thanks for reporting the issue. I have made an attempt to fix this issue in #23. If you can test the pull request that'd be great. I'll also test it and, if things go well, make a release later today.

**Comment by birnstiel** [comment]
wow that was fast! it works for my case.
