### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by astromark** [yymao/adstex#28]
Thanks for writing this code! I've been trying it out for the past week and it was working fine, but now I've encountered the following error when it reaches one of the references. Is there a way to determine which reference causes this? Perhaps it would be useful to have a way to skip to the next reference when such an error is encountered rather than quit the program?

> Traceback (most recent call last):
>   File "/astro/mark/anaconda2/envs/ads/bin/adstex", line 10, in <module>
>     sys.exit(main())
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 395, in main
>     bibcode_new = entry2bibcode(bib.entries_dict[key])
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 260, in entry2bibcode
>     id_this = id2bibcode(unquote(entry[field_name]), possible_id_types)
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 165, in id2bibcode
>     return next(s).bibcode
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/ads/search.py", line 501, in __next__
>     self.execute()
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/ads/search.py", line 532, in execute
>     self.response = SolrResponse.load_http_response(
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/ads/base.py", line 94, in load_http_response
>     raise APIResponseError(http_response.text)
> ads.exceptions.APIResponseError: '{\n  "error": "Not found"\n}\n'
>

**Comment by yymao** [comment]
Thanks for the report, @astromark! Please try adstex v0.3.9 and see if this issue is resolved. 

If not, please reopen this issue.

**Comment by astromark** [comment]
Thanks for the quick update. Unfortunately, I now get a different error.

> Traceback (most recent call last):
>   File "/astro/mark/anaconda2/envs/ads/bin/adstex", line 10, in <module>
>     sys.exit(main())
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 428, in main
>     bibcode = find_bibcode(key)
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 231, in find_bibcode
>     bibcode = authoryear2bibcode(fa, y, key)
>   File "/astro/mark/anaconda2/envs/ads/lib/python3.10/site-packages/adstex.py", line 195, in authoryear2bibcode
>     print(
> TypeError: 'extraline' is an invalid keyword argument for print()
> 

I presume this is because of the change made in 20b7c00. I'm not sure what bug you were trying to fix, but it seems to have introduced a new one.

**Comment by yymao** [comment]
Oops, sorry, my bad!  Please update to v0.3.10. Thanks for the report!

**Comment by astromark** [comment]
Everything works fine now. Thanks for the quick fix!
