### ISSUE TITLE
Update existing bibtex file

### ISSUE THREAD

**Issue by JohannesBuchner** [yymao/adstex#3]
Hi @yymao,

Really interesting project. I was wondering if you could support an even simpler use case:

If I give the program a ADS-derived bib file, it could look for updates to the entries, for example by adsurl entry. In that case, there is no TEX file.

It would help me update stale entries which I created based on arxiv submissions.

Cheers,
           Johannes

**Comment by yymao** [comment]
Thanks for the suggestion! Yep, it's indeed doable. I'll try finding time to implement this.

**Comment by JohannesBuchner** [comment]
Wow, that was quick! :)

**Comment by yymao** [comment]
@JohannesBuchner if you'd like to test out the new feature, you can download this file: https://raw.githubusercontent.com/yymao/adstex/issues/3-4-5/adstex.py

And just replace `adstex` with `python adstex.py` when you run it. For example:

```
python adstex.py your_bib_file.bib
```

I'll probably make a release later this week.
