### ISSUE TITLE
Bug: Failed to identify embeded citation keys of natbib

### ISSUE THREAD

**Issue by syrte** [yymao/adstex#41]
adstex (`search_keys`?) failed to identify `Diemer2018` as a citation in the following example:
```
\citet[with implementation by \citealt{Diemer2018}]{watson13}
```

**Comment by yymao** [comment]
Right, `adstex` does ignore anything between the brackets of a cite command.  I'll give it some thoughts but I am not sure if I'll be able to find a way around this as the regular expression is already quite complex at this point. 

Alternatively, you can change the tex source to the following for adstex to detect both citations. 

```tex
\citeauthor{watson13} (\citeyear{watson13}, with implementation by \citealt{Diemer2018})
```

**Comment by syrte** [comment]
Thanks for the workaround.
Sure, I guess this is only an uncommon edge case in practice.
