### ISSUE TITLE
Feature request: support for `@software` bibtex records for citing ASCL codes

### ISSUE THREAD

**Issue by kirxkirx** [yymao/adstex#42]
Would it be possible to add support for `@software` bibtex records for citing codes from [the Astrophysics Source Code Library (ASCL)](https://ascl.net/)? For example, I'm citing the ASCL record for `Fermitools` that I got from the [ADS](https://ui.adsabs.harvard.edu/abs/2019ascl.soft05011F/abstract):
````
@software{2019ascl.soft05011F,
       author = {{Fermi Science Support Development Team}},
        title = "{Fermitools: Fermi Science Tools}",
 howpublished = {Astrophysics Source Code Library, record ascl:1905.011},
         year = 2019,
        month = may,
          eid = {ascl:1905.011},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2019ascl.soft05011F},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
````
Unfortunately, when running on my paper source the `adstex` reports
````
Entry type software not standard. Not considered.
````
and ignores this record, so I have to insert it manually in the `.bib` file every time I re-reun `adstex`, which is a minor, but seemingly unnecessary inconvenience.

**Comment by yymao** [comment]
Thanks for the report. I am working on a fix in #43
