### ISSUE TITLE
Citation causes issues

### ISSUE THREAD

**Issue by birnstiel** [yymao/adstex#47]
I just tried to `\citet{Lau2022}` but this causes an error. The error message is:

```
"Query contains too many nested clauses; maxClauseCount is set to 2046"
```

Any other citations work well.

**Comment by yymao** [comment]
Thanks for the report. I can confirm this issue. Interestingly an error also occurs when searching this on ADS: https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(database%3Aastronomy%20OR%20database%3Aphysics)&q=%20%20first_author%3A%22Lau%22%20year%3A2022&sort=date%20desc%2C%20bibcode%20desc&p_=0

**Comment by birnstiel** [comment]
I don't get that error on ADS. 🤔 Your link just gets me to a results page with 86 entries.

**Comment by yymao** [comment]
Ah I copied the wrong link.  This link gave me an error: https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(database%3Aastronomy%20OR%20database%3Aphysics)&p_=0&q=%20%20author%3A%22^Lau%22%20year%3A2022&sort=date%20desc%2C%20bibcode%20desc

The difference between these two are the usage of `first_author` vs. `author:^`, so I am creating a PR #48 to see if that fixes things.
