### ISSUE TITLE
Pull the bibtex file from source if no "-o" is specified #feature-reqest

### ISSUE THREAD

**Issue by slosar** [yymao/adstex#5]
If no "-o" option is specified in the command line, just find the bibliography command in the source and pull it from there.

**Comment by yymao** [comment]
I'm implementing this, but there's two subtle issues:

1. `adstex` accepts multiple tex files at once, so this new feature will search for `\bibliography` in the some order as the file input, and stop at the first occurrence. This is not an issue for single tex input. 

2. `\bibliography` can have multiple bib files. So this feature will take the first one of the main file (i.e., equivalent to the one specified by `-o`) and the rest of supplement (i.e., equivalent to the ones specified by `-r`) .
